bets/urls.py
from django.conf.urls import url

from . import views

app_name = 'bets'

urlpatterns = [
    # Bet page
    url(
        r'^(?P<prim_key>[0-9]+)/$',
        views.bet_view,
        name='bet'
    ),

    # Place a bet
    url(
        r'^(?P<prim_key>[0-9]+)/bet$',
        views.place_bet,
        name='place_bet'
    ),

    # Resolve a bet
    url(
        r'^(?P<prim_key>[0-9]+)/resolve$',
        views.resolve_bet_view,
        name='resolve_bet'
    ),

    # Create ChoiceBet
    url(
        r'create/choice/$',
        views.create_choice_bet,
        name='create_choice_bet'
    ),

    # Edit ChoiceBet
    url(
        r'^(?P<pk>[0-9]+)/edit/choice/$',
        views.ChoiceBetUpdate.as_view(),
        name="edit_choice_bet"
    ),

    # Delete ChoiceBet
    url(
        r'^(?P<pk>[0-9]+)/delete/choice/$',
        views.ChoiceBetDelete.as_view(),
        name="delete_choice_bet"
    ),

    # Create DateBet
    url(
        r'^create/date/$',
        views.create_date_bet,
        name="create_date_bet"
    ),

    # Edit DateBet
    url(
        r'^(?P<pk>[0-9]+)/edit/date/$',
        views.DateBetUpdate.as_view(),
        name="edit_date_bet"
    ),

    # Delete DateBet
    url(
        r'^(?P<pk>[0-9]+)/delete/date/$',
        views.DateBetDelete.as_view(),
        name="delete_date_bet"
    ),
]

profiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'profiles'

urlpatterns = [
    url(
        r'^$',
        views.profile,
        name='profile'
    ),

    # Login mechanism
    url(
        r'^login/$',
        views.login_user,
        name='login'
    ),

    # Logout mechanism
    url(
        r'^logout/$',
        views.logout_user,
        name='logout'
    ),

    # Signup mechanism
    url(
        r'^signup/$',
        views.signup,
        name='signup'
    ),

    # Change Password
    url(
        r'^change_password/$',
        views.change_password,
        name='change_password'
    ),

    # General terms and conditions
    url(
        r'^general_terms_and_conditions/$',
        views.general_terms_and_conditions_view,
        name='general_terms_and_conditions'
    ),

    # Privacy policy
    url(
        r'^privacy_policy/$',
        views.privacy_policy_view,
        name='privacy_policy'
    ),

    # Provide feedback
    url(
        r'^feedback/$',
        views.feedback,
        name='feedback'
    ),

    # Resolve Feedback
    url(
        r'^feedback/(?P<id>[0-9]+)/resolve/$',
        views.resolve_feedback,
        name='resolve_feedback'
    ),

    # Deposit funds in account
    url(
        r'^payment/$',
        views.payment,
        name='payment'
    ),
]

the_platform/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import permission_required
from django.views.generic import TemplateView

from bets.views import index_view
from profiles.views import login_user, signup, feedback

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Index page
    url(r'^$', index_view, name='index'),

    # When the user goes to /login
    url(r'^login/', login_user),

    # When the user goes to /signup
    url(r'^signup/$', signup),

    # When the user goes to /feedback
    url(r'feedback/$', feedback),

    # Profiles sub-module
    url(r'^profile/', include('profiles.urls')),

    # Bets sub-module
    url(r'^bets/', include('bets.urls')),

    # Log view.
    url(
        r'^log/$',
        permission_required('admin')
        (TemplateView.as_view(template_name='the_platform/bbb.log', content_type='text/plain')),
        name='log'
    )
]

handler403 = views.error403
handler404 = views.error404
handler500 = views.error500

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

from ledger.models import Account


class Profile(models.Model):
    # The user that this profile is associated with
    # Since each profile is associated with exactly one user, the user is the profiles primary key
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    # Whether or not the users true identity has been verified
    verified = models.BooleanField(default=False)
    # Each user has an account
    account = models.OneToOneField(Account, on_delete=models.CASCADE)
    # Has the user accepted the general terms and conditions?
    accepted_general_terms_and_conditions = models.BooleanField(default=False)
    # Has the user accepted the privacy policy?
    accepted_privacy_policy = models.BooleanField(default=False)

    def __str__(self):
        return self.user.__str__()


class ForbiddenUser(models.Model):
    # The name that will be shown to the user making the selection
    name = models.CharField(max_length=64)
    # Whether this person actually has an account
    has_account = models.BooleanField()
    # If the person has an account, it will be linked here.
    account = models.OneToOneField(Profile, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    # User that provided the feedback
    provided_by = models.ForeignKey(User, on_delete=models.CASCADE)
    # The actual feedback
    feedback = models.TextField()
    # Is the feedback already resolved by the administrators?
    resolved = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

profiles/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Profile, Feedback
from ledger.models import Account, Transaction, Credit, Debit


class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': '30 characters or fewer. Letters, digits and @/./+/-/_ only.'
            }),
        }
        # TODO Update palceholders

    def clean_username(self):
        return self.cleaned_data.get('username').lower()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')

        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError(
                "This email address is already in use. Please supply a different email address.", code='email_in_use')
        return email

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        account = Account(name=user.username, type='p')
        account.save(commit)
        profile = Profile(user=user, account=account)
        profile.save(commit)
        return user


class LoginForm(AuthenticationForm):
    def clean_username(self):
        return self.cleaned_data.get('username').lower()


class PaymentForm(forms.Form):
    type = forms.ChoiceField(choices=[('d', 'Deposit'), ('w', 'Withdrawal')])
    account = forms.ModelChoiceField(queryset=User.objects.all())
    amount = forms.IntegerField(min_value=0)

    def clean_account(self):
        account = self.cleaned_data['account'].profile.account

        if not account.type == 'p':
            raise forms.ValidationError("Funds can only be deposited in personal accounts.",
                                        code='deposit_account_not_personal')

        return account

    def clean_amount(self):
        amount = self.cleaned_data['amount']

        if amount <= 0:
            raise forms.ValidationError(
                "This email address is already in use. Please supply a different email address.",
                code='deposit_amount_not_positive')

        if self.cleaned_data['type'] == 'w':
            account = self.cleaned_data['account']
            if account.compute_balance() < amount:
                raise forms.ValidationError("Insufficient funds.", code='insuficcient_funds')

        return self.cleaned_data['amount']

    def save(self, authorised, commit=True):
        user_account = self.cleaned_data['account']
        amount = self.cleaned_data['amount']

        if self.cleaned_data['type'] == 'w':
            system_account = Account.objects.get(name='withdrawal', type='o')
            if amount > 1:
                # TODO Find a transaction description convention
                description = "Withdrawal for " + str(amount) + " points\nAuthorised by: " + str(authorised)
            else:
                description = "Withdrawal for " + str(amount) + " point\nAuthorised by: " + str(authorised)

            transaction = Transaction(description=description)
            credit = Credit(transaction=transaction, account=system_account, amount=amount)
            debit = Debit(transaction=transaction, account=user_account, amount=amount)
        else:
            system_account = Account.objects.get(name='deposit', type='o')
            if amount > 1:
                description = "Deposit for " + str(amount) + " points\nAuthorised by: " + str(authorised)
            else:
                description = "Deposit for " + str(amount) + " point\nAuthorised by: " + str(authorised)

            transaction = Transaction(description=description)
            credit = Credit(transaction=transaction, account=user_account, amount=amount)
            debit = Debit(transaction=transaction, account=system_account, amount=amount)

        transaction.save(commit)
        credit.save(commit)
        debit.save(commit)

        user_account.compute_balance()
        system_account.compute_balance()

        return transaction


class FeedbackForm(forms.Form):
    feedback = forms.CharField(required=True, widget=forms.Textarea)

    def save(self, user, commit=True):
        assert isinstance(user, User)
        saved_feedback = Feedback(provided_by=user, feedback=self.cleaned_data['feedback'])
        saved_feedback.save(commit)

        return saved_feedback

profiles/views.py
import logging

from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.urls import reverse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect

from .forms import SignupForm, LoginForm, PaymentForm, FeedbackForm
from .models import Feedback
from bets.util import generate_profile_resolved_bet
from profiles.util import user_authenticated

logger = logging.getLogger(__name__)


@login_required
def profile(request):
    resolved_bets = generate_profile_resolved_bet(request.user.profile)
    return render(request, 'profiles/profile.html', {
        'resolved_placed_choice_bets': resolved_bets['resolved_placed_choice_bets'],
        'resolved_placed_date_bets': resolved_bets['resolved_placed_date_bets'],
        'feedback': Feedback.objects.filter(resolved=False)
    })


def login_user(request):
    if user_authenticated(request.user):
        return redirect('index')
    else:
        if request.method == 'POST':
            form = LoginForm(data=request.POST)
            if form.is_valid():
                login(request, form.get_user())
                return redirect('index')
        else:
            form = LoginForm()

        return render(request, 'profiles/login.html', {'form': form})


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, "Logout successful")
    return redirect('profiles:login')


def signup(request):
    if user_authenticated(request.user):
        return redirect('index')
    else:
        if request.method == 'POST':
            form = SignupForm(request.POST)
            if form.is_valid():
                user = form.save()
                user.profile.accepted_general_terms_and_conditions = True
                user.profile.accepted_privacy_policy = True
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                user.profile.save()
                login(request, user)
                messages.info(request, "You're not authenticated. Please get in contact with an administrator.")
                return redirect('profiles:profile')
        else:
            form = SignupForm()

        return render(request, 'profiles/signup.html', {'form': form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            # TODO add this "(update_session_auth_hash(request, form.user))"? It's mentioned in docs.
            return redirect(login_user)
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'profiles/change_password.html', {'form': form})


@login_required
def payment(request):
    if user_authenticated(request.user) and request.user.is_superuser:
        if request.method == 'POST':
            form = PaymentForm(request.POST)
            if form.is_valid():
                transaction = form.save(authorised=request.user)
                messages.success(request, transaction.description)
                return render(request, 'profiles/payment.html', {'form': PaymentForm()})
        else:
            form = PaymentForm()
            return render(request, 'profiles/payment.html', {'form': form})
    else:
        messages.info(request, "You're not authenticated. Please get in contact with an administrator.")
        if not request.user.is_anonymous:
            logger.warning("Unverified user " + request.user.username + " tried to view payment page.")
            return redirect('profiles:profile')
        raise PermissionDenied


def general_terms_and_conditions_view(request):
    if user_authenticated(request.user) or request.user.is_authenticated:
        return render(request, 'profiles/general_terms_and_conditions.html')
    else:
        return render(request, 'profiles/general_terms_and_conditions_anonymous.html')


def privacy_policy_view(request):
    if user_authenticated(request.user) or request.user.is_authenticated:
        return render(request, 'profiles/privacy_policy.html')
    else:
        return render(request, 'profiles/privacy_policy_anonymous.html')


@login_required
def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save(user=request.user)
            messages.success(request, "Thank you for your valuable feedback. We will use it to make BBB even better.")
            return redirect('profiles:profile')
    else:
        form = FeedbackForm()

    return render(request, 'profiles/feedback.html', {
        'form': form,
        'resolved_feedback': request.user.feedback_set.filter(resolved=True),
        'unresolved_feedback': request.user.feedback_set.filter(resolved=False),
    })


@login_required
def resolve_feedback(request, id):
    try:
        feedback = Feedback.objects.get(id=id)
        feedback.resolved = True
        feedback.save()
    except Feedback.DoesNotExist:
        messages.info(request, "Feedback does not exist")
        raise Http404
    return HttpResponseRedirect(reverse('profiles:profile'))

profiles/templates/profiles/change_password.html
{% extends 'the_platform/base.html' %}

{% block title %}
    Change Password | {{ block.super }}
{% endblock %}

{% block links %}
    <ul>
        <li>
            <a href="{% url 'profiles:feedback' %}">Feedback</a>
        </li>
        <li>
            <a>Create Bet</a>
            <menu>
                <menuitem>
                    <a href="{% url 'bets:create_choice_bet' %}">Choice Bet</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'bets:create_date_bet' %}">Date Bet</a>
                </menuitem>
            </menu>
        </li>
        <li>
            <a>{{ user.profile }}</a>
            <menu>
                <menuitem>
                    <a href="{% url 'profiles:profile' %}">Profile</a>
                </menuitem>
                {% if user.is_superuser %}
                    <menuitem>
                        <a href="{% url 'profiles:profile' %}#unresolved_feedback">Unresolved Feedback</a>
                    </menuitem>
                {% endif %}
                <menuitem>
                    <a href="{% url 'profiles:profile' %}#transactions">Transactions</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'profiles:profile' %}#resolved_bets">Resolved Bets</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'profiles:logout' %}">Logout</a>
                </menuitem>
            </menu>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <form action="{% url 'profiles:change_password' %}" method="post">
        {% csrf_token %}

        <card>
            <h2 xx class="centered">Change password</h2>
            <table>
                {{ form.as_table }}
            </table>
        </card>

        <button primary full>Change Password</button>
    </form>
{% endblock %}

profiles/templates/profiles/deposit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deposit</title>
</head>
<body>
<form action="{% url 'profiles:deposit' %}" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input type="submit" value="Submit">
</form>
</body>
</html>

profiles/templates/profiles/feedback.html
{% extends 'the_platform/base.html' %}

{% block title %}
    Feedback | {{ block.super }}
{% endblock %}

{% block links %}
    <ul>
        <li>
            <a href="{% url 'profiles:feedback' %}">Feedback</a>
        </li>
        <li>
            <a>Create Bet</a>
            <menu>
                <menuitem>
                    <a href="{% url 'bets:create_choice_bet' %}">Choice Bet</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'bets:create_date_bet' %}">Date Bet</a>
                </menuitem>
            </menu>
        </li>
        <li>
            <a>{{ user.profile }}</a>
            <menu>
                <menuitem>
                    <a href="{% url 'profiles:profile' %}">Profile</a>
                </menuitem>
                {% if user.is_superuser %}
                    <menuitem>
                        <a href="{% url 'profiles:profile' %}#unresolved_feedback">Unresolved Feedback</a>
                    </menuitem>
                {% endif %}
                <menuitem>
                    <a href="{% url 'profiles:profile' %}#transactions">Transactions</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'profiles:profile' %}#resolved_bets">Resolved Bets</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'profiles:logout' %}">Logout</a>
                </menuitem>
            </menu>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <card>
        <form action="{% url 'profiles:feedback' %}" method="POST">
            {% csrf_token %}
            <h2 xx class="centered">Feedback</h2>
            {{ form.feedback }}
            <button primary full>Send Feedback</button>
        </form>
    </card>
    <hr>
    <grid>
        <div col="1/2" class="border_right">
            <h2 xx class="centered">Unresolved Feedback</h2>
            {% if unresolved_feedback %}
                {% for entry in unresolved_feedback %}
                    <card>
                        <p class="formatted hyphenate">{{ entry.feedback }}</p>
                    </card>
                {% endfor %}
            {% else %}
                <h5 xx class="centered">No unresolved feedback is available</h5>
            {% endif %}
        </div>
        <div col="1/2" class="border_left">
            <h2 xx class="centered">Resolved Feedback</h2>
            {% if resolved_feedback %}
                {% for entry in resolved_feedback %}
                    <card>
                        <p class="formatted hyphenate">{{ entry.feedback }}</p>
                    </card>
                {% endfor %}
            {% else %}
                <h5 xx class="centered">No resolved feedback is available</h5>
            {% endif %}
        </div>
    </grid>
{% endblock %}

profiles/templates/profiles/payment.html
{% extends 'the_platform/base.html' %}

{% block title %}
    Payment | {{ block.super }}
{% endblock %}

{% block links %}
    <ul>
        <li>
            <a href="{% url 'profiles:feedback' %}">Feedback</a>
        </li>
        <li>
            <a>Create Bet</a>
            <menu>
                <menuitem>
                    <a href="{% url 'bets:create_choice_bet' %}">Choice Bet</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'bets:create_date_bet' %}">Date Bet</a>
                </menuitem>
            </menu>
        </li>
        <li>
            <a>{{ user.profile }}</a>
            <menu>
                <menuitem>
                    <a href="{% url 'profiles:profile' %}">Profile</a>
                </menuitem>
                {% if user.is_superuser %}
                    <menuitem>
                        <a href="{% url 'profiles:profile' %}#unresolved_feedback">Unresolved Feedback</a>
                    </menuitem>
                {% endif %}
                <menuitem>
                    <a href="{% url 'profiles:profile' %}#transactions">Transactions</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'profiles:profile' %}#resolved_bets">Resolved Bets</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'profiles:logout' %}">Logout</a>
                </menuitem>
            </menu>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <form action="{% url 'profiles:payment' %}" method="POST">
        {% csrf_token %}
        <card>
            <h2 xx class="centered">Execute Transaction</h2>
            <table>
                {{ form.as_table }}
            </table>
        </card>
        <button primary full>Submit</button>
    </form>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'the_platform/base.html' %}

{% block title %}
    {{ user.profile }} | {{ block.super }}
{% endblock %}

{% block links %}
    <ul>
        <li>
            <a href="{% url 'profiles:feedback' %}">Feedback</a>
        </li>
        <li>
            <a>Create Bet</a>
            <menu>
                <menuitem>
                    <a href="{% url 'bets:create_choice_bet' %}">Choice Bet</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'bets:create_date_bet' %}">Date Bet</a>
                </menuitem>
            </menu>
        </li>
        <li>
            <a>{{ user.profile }}</a>
            <menu>
                <menuitem>
                    <a href="{% url 'profiles:profile' %}">Profile</a>
                </menuitem>
                {% if user.is_superuser %}
                    <menuitem>
                        <a href="{% url 'profiles:profile' %}#unresolved_feedback">Unresolved Feedback</a>
                    </menuitem>
                {% endif %}
                <menuitem>
                    <a href="{% url 'profiles:profile' %}#transactions">Transactions</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'profiles:profile' %}#resolved_bets">Resolved Bets</a>
                </menuitem>
                <menuitem>
                    <a href="{% url 'profiles:logout' %}">Logout</a>
                </menuitem>
            </menu>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <card>
        <table>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Account Balance</th>
                <td>{{ user.profile.account.balance }}</td>
            </tr>
        </table>
        <form action="{% url 'profiles:change_password' %}" method="post">
            {% csrf_token %}
            <button primary full>Change Password</button>
        </form>
    </card>

    {% if user.is_superuser %}
        <grid>
            <div col="1/2">
                <form action="{% url 'log' %}">
                    {% csrf_token %}
                    <button full>View log</button>
                </form>
            </div>
            <div col="1/2">
                <form action="{% url 'profiles:payment' %}">
                    {% csrf_token %}
                    <button full>Payment</button>
                </form>
            </div>
        </grid>
        <hr>
        <h2 xx class="centered" id="unresolved_feedback">Unresolved Feedback</h2>
        {% if feedback %}
            {% for entry in feedback %}
                <card>
                    <p>Feedback from {{ entry.provided_by }}</p>
                    <hr>
                    <p class="formatted hyphenate">{{ entry.feedback }}</p>
                    <form action="{% url 'profiles:resolve_feedback' entry.id %}" method="post">
                        {% csrf_token %}
                        <button
                            primary
                            full
                            name="{{ entry.prim_key }}"
                            onclick="return confirm('Are you sure? Feedback (ID ' + {{ entry.id }} +
                                ') will be resolved.')"
                        >
                            Resolve
                        </button>
                    </form>
                </card>
            {% endfor %}
        {% else %}
            <h5 xx class="centered">There is no unresolved feedback</h5>
        {% endif %}
    {% endif %}
    <hr>
    <card id="transactions">
        <grid>
            <div col="1/2" class="border_right">
                <h2 xx class="centered">Credit</h2>
                {% if user.profile.account.credit_set.all %}
                    <table>
                        <thead>
                        <tr>
                            <th>Transaction</th>
                            <th>Amount</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for credit in user.profile.account.credit_set.all %}
                            <tr>
                                <td class="formatted hyphenate">{{ credit.transaction.description }}</td>
                                <td>{{ credit.amount }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h5 xx class="centered">There are no credits yet</h5>
                {% endif %}
            </div>
            <div col="1/2" class="border_left">
                <h2 xx class="centered">Debit</h2>
                {% if user.profile.account.debit_set.all %}
                    <table>
                        <thead>
                        <tr>
                            <th>Transaction</th>
                            <th>Amount</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for debit in user.profile.account.debit_set.all %}
                            <tr>
                                <td class="formatted hyphenate">{{ debit.transaction.description }}</td>
                                <td>{{ debit.amount }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h5 xx class="centered">There are no debits yet</h5>
                {% endif %}
            </div>
        </grid>
    </card>
    <hr>
    <div id="resolved_bets">
        <grid>
            <div col="1/2" class="border_right">
                <h2 xx class="centered">Resolved Choice Bets</h2>
                {% for resolved_bet in resolved_placed_choice_bets %}
                    <a class="card_link" href="{% url 'bets:bet' resolved_bet.placed_on.prim_key %}">
                        <card>
                            <h5 xx class="formatted hyphenate">{{ resolved_bet.placed_on.name }}</h5>
                            <hr>
                            <grid>
                                <div col="1/2" class="border_right">
                                    <p xx class="formatted hyphenate">{{ resolved_bet.placed_on.description }}</p>
                                </div>
                                <div col="1/2" class="border_left">
                                    <p class="inline">Winning choice:</p>
                                    <p xx class="formatted hyphenate">{{ resolved_bet.placed_on.winning_choice }}</p>
                                    <p class="inline">Your choice:</p>
                                    <p xx class="formatted hyphenate">{{ resolved_bet.chosen }}</p>
                                    {% if resolved_bet.chosen == resolved_bet.placed_on.winning_choice %}
                                        {# TODO "Won x points" #}
                                        <p>You won.</p>
                                    {% else %}
                                        <p>You placed on the wrong choice and lost {{ resolved_bet.placed }} points.</p>
                                    {% endif %}
                                </div>
                            </grid>
                        </card>
                    </a>
                {% empty %}
                    <h5 xx class="centered">There are not resolved choice bets yet</h5>
                {% endfor %}
            </div>
            <div col="1/2" class="border_left">
                <h2 xx class="centered">Resolved Date Bets</h2>
                {% for resolved_bet in resolved_placed_date_bets %}
                    <a class="card_link" href="{% url 'bets:bet' resolved_bet.placed_on.prim_key %}">
                        <card>
                            <h5 xx class="formatted hyphenate">{{ resolved_bet.placed_on.name }}</h5>
                            <hr>
                            <grid>
                                <div col="1/2" class="border_right">
                                    <p xx class="formatted hyphenate">{{ resolved_bet.placed_on.description }}</p>
                                </div>
                                <div col="1/2" class="border_left">
                                    <p>Winning date:<br> {{ resolved_bet.placed_on.winning_date }}</p>
                                    <p>Your date:<br> {{ resolved_bet.placed_date }}</p>
                                    <p>Placed: {{ resolved_bet.placed }}</p>
                                    {# TODO won/lost #}
                                </div>
                            </grid>
                        </card>
                    </a>
                {% empty %}
                    <h5 xx class="centered">There are no resolved date bets yet</h5>
                {% endfor %}
            </div>
        </grid>
    </div>
{% endblock %}