bets/urls.py
from django.conf.urls import url

from . import views

app_name = 'bets'

urlpatterns = [
    # Bet page
    url(
        r'^(?P<prim_key>[0-9]+)/$',
        views.bet_view,
        name='bet'
    ),

    # Place a bet
    url(
        r'^(?P<prim_key>[0-9]+)/bet$',
        views.place_bet,
        name='place_bet'
    ),

    # Resolve a bet
    url(
        r'^(?P<prim_key>[0-9]+)/resolve$',
        views.resolve_bet_view,
        name='resolve_bet'
    ),

    # Create ChoiceBet
    url(
        r'create/choice/$',
        views.create_choice_bet,
        name='create_choice_bet'
    ),

    # Edit ChoiceBet
    url(
        r'^(?P<pk>[0-9]+)/edit/choice/$',
        views.ChoiceBetUpdate.as_view(),
        name="edit_choice_bet"
    ),

    # Delete ChoiceBet
    url(
        r'^(?P<pk>[0-9]+)/delete/choice/$',
        views.ChoiceBetDelete.as_view(),
        name="delete_choice_bet"
    ),

    # Create DateBet
    url(
        r'^create/date/$',
        views.create_date_bet,
        name="create_date_bet"
    ),

    # Edit DateBet
    url(
        r'^(?P<pk>[0-9]+)/edit/date/$',
        views.DateBetUpdate.as_view(),
        name="edit_date_bet"
    ),

    # Delete DateBet
    url(
        r'^(?P<pk>[0-9]+)/delete/date/$',
        views.DateBetDelete.as_view(),
        name="delete_date_bet"
    ),
]

profiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'profiles'

urlpatterns = [
    url(
        r'^$',
        views.profile,
        name='profile'
    ),

    # Login mechanism
    url(
        r'^login/$',
        views.login_user,
        name='login'
    ),

    # Logout mechanism
    url(
        r'^logout/$',
        views.logout_user,
        name='logout'
    ),

    # Signup mechanism
    url(
        r'^signup/$',
        views.signup,
        name='signup'
    ),

    # Change Password
    url(
        r'^change_password/$',
        views.change_password,
        name='change_password'
    ),

    # General terms and conditions
    url(
        r'^general_terms_and_conditions/$',
        views.general_terms_and_conditions_view,
        name='general_terms_and_conditions'
    ),

    # Privacy policy
    url(
        r'^privacy_policy/$',
        views.privacy_policy_view,
        name='privacy_policy'
    ),

    # Provide feedback
    url(
        r'^feedback/$',
        views.feedback,
        name='feedback'
    ),

    # Resolve Feedback
    url(
        r'^feedback/(?P<id>[0-9]+)/resolve/$',
        views.resolve_feedback,
        name='resolve_feedback'
    ),

    # Deposit funds in account
    url(
        r'^payment/$',
        views.payment,
        name='payment'
    ),
]

the_platform/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import permission_required
from django.views.generic import TemplateView

from bets.views import index_view
from profiles.views import login_user, signup, feedback

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Index page
    url(r'^$', index_view, name='index'),

    # When the user goes to /login
    url(r'^login/', login_user),

    # When the user goes to /signup
    url(r'^signup/$', signup),

    # When the user goes to /feedback
    url(r'feedback/$', feedback),

    # Profiles sub-module
    url(r'^profile/', include('profiles.urls')),

    # Bets sub-module
    url(r'^bets/', include('bets.urls')),

    # Log view.
    url(
        r'^log/$',
        permission_required('admin')
        (TemplateView.as_view(template_name='the_platform/bbb.log', content_type='text/plain')),
        name='log'
    )
]

handler403 = views.error403
handler404 = views.error404
handler500 = views.error500

the_platform/views.py
from django.shortcuts import render

from profiles.util import user_authenticated


def error403(request):
    return render(request, 'the_platform/403.html', {
        'user_authenticated': user_authenticated(request.user)
    })


def error404(request):
    return render(request, 'the_platform/404.html', {
        'user_authenticated': user_authenticated(request.user)
    })


def error500(request):
    return render(request, 'the_platform/500.html', {
        'user_authenticated': user_authenticated(request.user)
    })

the_platform/templates/the_platform/base.html
{% load staticfiles %}
<html lang="de">
<head>
    <title>{% block title %}Bad Bat Bets{% endblock %}</title>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <meta name="theme-color" content="#679">

    <link rel="stylesheet" href="{% static 'the_platform/css/style.css' %}">
    <link rel="icon" href="{% static 'the_platform/icons/favicon.ico' %}">

    <script src="{% static 'the_platform/js/hyphenator.js' %}"></script>
</head>
<body>
<main>
    <nav fx>
        <label>
            <input type="checkbox">
            <header>
                <a href="{% url 'index' %}"><img src="{% static 'the_platform/icons/logo.svg' %}">Bad Bat Bets</a>
            </header>
            {% block links %}
                <ul>
                    <li><a href="{% url 'profiles:login' %}">Login</a></li>
                    <li><a href="{% url 'profiles:signup' %}">Signup</a></li>
                </ul>
            {% endblock %}
        </label>
    </nav>

    <section>
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.DEBUG %}
                    <card id="debug" onclick='this.parentNode.removeChild(this); return false;'>
                        <grid>
                            <div col="1/6" class="border_right total_center">
                                <strong>DEBUG</strong>
                            </div>
                            <div col="5/6" class="border_left">
                                <strong class="formatted hyphenate">{{ message }}</strong>
                            </div>
                        </grid>
                    </card>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                    <card id="info" onclick='this.parentNode.removeChild(this); return false;'>
                        <grid>
                            <div col="1/6" class="border_right total_center">
                                <strong>INFO</strong>
                            </div>
                            <div col="5/6" class="border_left">
                                <strong class="formatted hyphenate">{{ message }}</strong>
                            </div>
                        </grid>
                    </card>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <card id="success" onclick='this.parentNode.removeChild(this); return false;'>
                        <grid>
                            <div col="1/6" class="border_right total_center">
                                <strong>SUCCESS</strong>
                            </div>
                            <div col="5/6" class="border_left">
                                <strong class="formatted hyphenate">{{ message }}</strong>
                            </div>
                        </grid>
                    </card>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                    <card id="warning" onclick='this.parentNode.removeChild(this); return false;'>
                        <grid>
                            <div col="1/6" class="border_right total_center">
                                <strong>WARNING</strong>
                            </div>
                            <div col="5/6" class="border_left">
                                <strong class="formatted hyphenate">{{ message }}</strong>
                            </div>
                        </grid>
                    </card>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <card id="error" onclick='this.parentNode.removeChild(this); return false;'>
                        <grid>
                            <div col="1/6" class="border_right total_center">
                                <strong>ERROR</strong>
                            </div>
                            <div col="5/6" class="border_left">
                                <strong class="formatted hyphenate">{{ message }}</strong>
                            </div>
                        </grid>
                    </card>
                {% endif %}
            {% endfor %}
        {% endif %}

        {% block content %}{% endblock %}
    </section>

    <footer>
        <grid>
            <div col="1/2">
                <p>&copy; Fusion Integrals {% now "Y" %}</p>
            </div>
            <div col="1/2" txt="r" id="agreements">
                <p>
                    <a href="{% url 'profiles:general_terms_and_conditions' %}">General terms and conditions</a>
                    <a href="{% url 'profiles:privacy_policy' %}">Privacy policy</a>
                </p>
            </div>
        </grid>
    </footer>
</main>
</body>
</html>